version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '$PORT:$PORT'
    links:
      - mongo
    environment:
      ROOT_URL: ${ROOT_URL:-http://localhost}
      MONGO_URL: ${MONGO_URL:-mongodb://mongo:27017/meteor}
      PORT: $PORT
      HTTP_FORWARDED_COUNT: ${HTTP_FORWARDED_COUNT:-0}
      MAIL_URL: ${MAIL_URL:-}
      METEOR_SETTINGS: ${METEOR_SETTINGS:-}
      MONGO_OPLOG_URL: ${MONGO_OPLOG_URL:-} # like so: mongodb://user:password@myserver.com:10139/local?replicaSet=(your replica set)&authSource=(your auth source)

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
